name: Integration Test

on:
    push:
        branches: [main]
    pull_request:

jobs:
    integration-test:
        runs-on: ubuntu-latest

        services:
            docker:
                image: docker:24.0.2
                options: --privileged

        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Setup Docker Compose
              run: |
                sudo apt update
                sudo apt install -y docker-compose

            - name: Build and Start Services
              run: docker-compose up -d --build

            - name: Wait for Service A health
              run: |
                    docker-compose ps
                    docker-compose exec -T service-a curl -s http://localhost:5000/trigger

            - name: Run integration tests
              run: |
                pip3 install requests pytest
                pytest tests/test_integration.py

            - name: Shut down services
              run: docker-compose down